DELETE FROM IF EXISTS film_likes;
DELETE FROM IF EXISTS film_genres;
DELETE FROM IF EXISTS films;
DELETE FROM IF EXISTS friendships;
DELETE FROM IF EXISTS users;
DELETE FROM IF EXISTS genres;
DELETE FROM IF EXISTS mpa_ratings;